### ISSUE TITLE
上传图片失败。

### ISSUE THREAD

**Issue by SwingWillwow** [zhangmazi/laravel-ueditor#1]
各位大佬还有作者你们好，我在使用这个包的过程中，不能上传图片，提示上传错误，但是在我指定的上传目录下已经生成了对应的图片文件，不知道是什么原因，希望有人能给我解答一下，谢谢。 @zhangmazi

**Comment by zhaozidong86** [comment]
我也碰到相同的问题了，用的的aws s3，上传图片不成功 ,（驱动改成本地可以成功）不知道是哪里出了问题，忘作者能不能抽空解答一下，谢谢。

**Comment by zhangmazi** [comment]
谢谢你们提示，由于公司项目和这个源码有混了，上次版本改错了。这次v1.0.5已经修复。请你们再试试。

**Comment by zhangmazi** [comment]
close issue
